;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                                                            ;
;                                  MTRMAIN.INC                               ;
;                           Include for Motor Main Loop                      ;
;                                   EE/CS 51                                 ;
;                                   Yuan Ma 	                             ;
;                                                                            ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
; File Description:
;      This file contains the constants used in the motor board functions. 
;
;
; Revision History:
;      12/11/15      Yuan Ma	    initial revision 
;
;
; Constant definitions for remote functions:
  
MOTOR_SYMBOL       EQU  'n'     ;used twice to simulate an m to indicate motor
LASER_SYMBOL       EQU  'L'     ;indicate a laser status 
DIRECTION_SYMBOL   EQU  'd'     ;indicate a direction status 
SPEED_SYMBOL       EQU  'S'     ;indicate a speed status  
